"""Initial migration: create unified_tasks, user_integrations, and task_dependencies tables

Revision ID: 7084e0d45639
Revises: 
Create Date: 2025-07-16 06:44:37.499757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7084e0d45639'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'MICROSOFT_TEAMS', 'MICROSOFT_PLANNER', 'NOTION', 'EXCEL_IMPORT', name='tasksource'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_tasks_id'), 'unified_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_unified_tasks_user_id'), 'unified_tasks', ['user_id'], unique=False)
    op.create_table('user_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sync_frequency', sa.Interval(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_id'), 'user_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('parent_task_id', sa.String(), nullable=False),
    sa.Column('child_task_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'SUBTASK', 'RELATED', name='dependencytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['unified_tasks.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['unified_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_user_id'), 'task_dependencies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_user_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_unified_tasks_user_id'), table_name='unified_tasks')
    op.drop_index(op.f('ix_unified_tasks_id'), table_name='unified_tasks')
    op.drop_table('unified_tasks')
    # ### end Alembic commands ###
